#!/usr/bin/env python3
"""Batch add hundreds of new links across all categories"""
import json, os, sys

LINKS_FILE = 'links.json'
JS_FILE = 'links.js'

with open(LINKS_FILE) as f:
    links = json.load(f)

existing_urls = {l['url'] for l in links}
added = 0
new_links_list = []

def add(name, url, desc, category):
    global added
    if url in existing_urls:
        return
    new_links_list.append({"name": name, "url": url, "desc": desc, "category": category})
    existing_urls.add(url)
    added += 1

# ============ ASTRONOMY ============
add("NASA", "https://www.nasa.gov/", "National Aeronautics and Space Administration", "Astronomy")
add("ESA", "https://www.esa.int/", "European Space Agency", "Astronomy")
add("Space.com", "https://www.space.com/", "Space news and exploration", "Astronomy")
add("Sky & Telescope", "https://skyandtelescope.org/", "Astronomy observing and equipment", "Astronomy")
add("Astronomy Magazine", "https://www.astronomy.com/", "Leading astronomy magazine", "Astronomy")
add("Stellarium", "https://stellarium.org/", "Free open-source planetarium", "Astronomy")
add("Heavens-Above", "https://www.heavens-above.com/", "Satellite tracking and ISS visibility", "Astronomy")
add("SpaceWeatherLive", "https://www.spaceweatherlive.com/", "Solar activity and aurora forecasts", "Astronomy")
add("Hubble Site", "https://hubblesite.org/", "Hubble Space Telescope images", "Astronomy")
add("NASA APOD", "https://apod.nasa.gov/", "Astronomy Picture of the Day", "Astronomy")
add("JPL Solar System", "https://ssd.jpl.nasa.gov/", "Solar system data and ephemeris", "Astronomy")
add("SETI Institute", "https://www.seti.org/", "Search for extraterrestrial intelligence", "Astronomy")
add("Celestia", "https://celestia.space/", "Real-time 3D space simulation", "Astronomy")
add("Cloudy Nights", "https://www.cloudynights.com/", "Amateur astronomy forum", "Astronomy")
add("AstroBin", "https://www.astrobin.com/", "Astrophotography hosting", "Astronomy")
add("In-The-Sky", "https://in-the-sky.org/", "Sky charts and astronomy guides", "Astronomy")
add("Space Engine", "https://spaceengine.org/", "Universal 3D space simulator", "Astronomy")
add("NASA Exoplanets", "https://exoplanets.nasa.gov/", "Exoplanet discovery and data", "Astronomy")
add("Solar System Scope", "https://www.solarsystemscope.com/", "Interactive solar system model", "Astronomy")

# ============ BIRDWATCHING ============
add("eBird", "https://ebird.org/", "Global bird observation database", "Birdwatching")
add("All About Birds", "https://www.allaboutbirds.org/", "Cornell bird guide and sounds", "Birdwatching")
add("BirdForum", "https://www.birdforum.net/", "Largest bird watching community", "Birdwatching")
add("Audubon Society", "https://www.audubon.org/", "Bird conservation and guides", "Birdwatching")
add("Xeno-canto", "https://xeno-canto.org/", "Community bird sound database", "Birdwatching")
add("Fat Birder", "https://fatbirder.com/", "Worldwide birding directory", "Birdwatching")
add("Birds of the World", "https://birdsoftheworld.org/", "Comprehensive bird species accounts", "Birdwatching")
add("RSPB", "https://www.rspb.org.uk/", "Royal Society for Bird Protection", "Birdwatching")
add("Surfbirds", "https://www.surfbirds.com/", "Birding trip reports", "Birdwatching")
add("BirdLife International", "https://www.birdlife.org/", "Global bird conservation", "Birdwatching")
add("WhatBird", "https://www.whatbird.com/", "Bird identification and forum", "Birdwatching")
add("Avibase", "https://avibase.bsc-eoc.org/", "World bird database", "Birdwatching")
add("Hawk Mountain", "https://www.hawkmountain.org/", "Raptor conservation and research", "Birdwatching")
add("Merlin Bird ID", "https://merlin.allaboutbirds.org/", "Free bird identification app", "Birdwatching")
add("Project FeederWatch", "https://feederwatch.org/", "Citizen science bird counting", "Birdwatching")

# ============ ELECTRONICS ============
add("SparkFun", "https://www.sparkfun.com/", "Electronics tutorials and components", "Electronics")
add("Adafruit", "https://www.adafruit.com/", "Electronics learning system", "Electronics")
add("DigiKey", "https://www.digikey.com/", "Electronic component distributor", "Electronics")
add("Mouser Electronics", "https://www.mouser.com/", "Electronic components distributor", "Electronics")
add("KiCad", "https://www.kicad.org/", "Open-source PCB design software", "Electronics")
add("EasyEDA", "https://easyeda.com/", "Web-based PCB design", "Electronics")
add("All About Circuits", "https://www.allaboutcircuits.com/", "Electronics education resources", "Electronics")
add("Electronics Tutorials", "https://www.electronics-tutorials.ws/", "Basic electronics tutorials", "Electronics")
add("Falstad Circuit", "https://www.falstad.com/circuit/", "Interactive circuit simulator", "Electronics")
add("Build Electronic Circuits", "https://www.build-electronic-circuits.com/", "Learn electronics projects", "Electronics")
add("Circuit Basics", "https://www.circuitbasics.com/", "Arduino and electronics projects", "Electronics")
add("Tindie", "https://www.tindie.com/", "Marketplace for electronics creators", "Electronics")
add("Hackaday.io", "https://hackaday.io/", "Hardware hacking community", "Electronics")
add("OSH Park", "https://oshpark.com/", "Purple PCB fabrication service", "Electronics")
add("JLCPCB", "https://jlcpcb.com/", "Low-cost PCB prototyping", "Electronics")
add("PCBWay", "https://www.pcbway.com/", "PCB manufacturing service", "Electronics")
add("Electro Tech", "https://www.electro-tech-online.com/", "Electronics community forum", "Electronics")
add("Stack Exchange EE", "https://electronics.stackexchange.com/", "Q&A for electronics", "Electronics")
add("OctoPart", "https://octopart.com/", "Electronic part search engine", "Electronics")

# ============ ROBOTICS ============
add("ROS", "https://www.ros.org/", "Robot Operating System framework", "Robotics")
add("RobotShop", "https://www.robotshop.com/", "Robotics parts and community", "Robotics")
add("RoboDK", "https://robodk.com/", "Robot simulation software", "Robotics")
add("Arduino", "https://www.arduino.cc/", "Open-source electronics platform", "Robotics")
add("FIRST Robotics", "https://www.firstinspires.org/", "Youth robotics competition", "Robotics")
add("Robotics Stack Exchange", "https://robotics.stackexchange.com/", "Q&A for robotics", "Robotics")
add("Let's Make Robots", "https://letsmakerobots.com/", "Robot building community", "Robotics")
add("IEEE RAS", "https://www.ieee-ras.org/", "Robotics and automation society", "Robotics")
add("Open Robotics", "https://www.openrobotics.org/", "Open-source robotics software", "Robotics")
add("The Construct", "https://www.theconstruct.ai/", "ROS robotics simulation courses", "Robotics")
add("Pololu", "https://www.pololu.com/", "Robotics components store", "Robotics")
add("Gazebo Simulator", "https://gazebosim.org/", "Multi-robot simulator", "Robotics")
add("Robotics.org", "https://www.robotics.org/", "Advancing automation association", "Robotics")
add("Robot Ignite Academy", "https://www.robotigniteacademy.com/", "ROS learning platform", "Robotics")
add("ROS 2 Documentation", "https://docs.ros.org/", "ROS 2 official documentation", "Robotics")

# ============ LANGUAGE LEARNING ============
add("Duolingo", "https://www.duolingo.com/", "Free gamified language learning", "Language Learning")
add("Anki", "https://apps.ankiweb.net/", "Spaced repetition flashcards", "Language Learning")
add("Memrise", "https://www.memrise.com/", "Language learning with SRS", "Language Learning")
add("Clozemaster", "https://www.clozemaster.com/", "Context-based language learning", "Language Learning")
add("LingQ", "https://www.lingq.com/", "Learn through content you love", "Language Learning")
add("Busuu", "https://www.busuu.com/", "Learning with native feedback", "Language Learning")
add("HelloTalk", "https://www.hellotalk.com/", "Language exchange with natives", "Language Learning")
add("Tandem", "https://www.tandem.net/", "Language exchange partners", "Language Learning")
add("Italki", "https://www.italki.com/", "Find language tutors online", "Language Learning")
add("Forvo", "https://forvo.com/", "Pronunciation by native speakers", "Language Learning")
add("WordReference", "https://www.wordreference.com/", "Online multilingual dictionary", "Language Learning")
add("Babbel", "https://www.babbel.com/", "Subscription language learning", "Language Learning")
add("Pimsleur", "https://www.pimsleur.com/", "Audio-based language learning", "Language Learning")
add("FluentU", "https://www.fluentu.com/", "Learn with real-world videos", "Language Learning")
add("Reverso Context", "https://context.reverso.net/", "Context translation examples", "Language Learning")
add("Lingua.com", "https://lingua.com/", "Reading and comprehension practice", "Language Learning")
add("Preply", "https://www.preply.com/", "Online language tutors platform", "Language Learning")

# ============ COOKING ============
add("Serious Eats", "https://www.seriouseats.com/", "Science-based cooking and recipes", "Cooking")
add("AllRecipes", "https://www.allrecipes.com/", "User-submitted recipe collection", "Cooking")
add("Epicurious", "https://www.epicurious.com/", "Gourmet recipes and inspiration", "Cooking")
add("Food52", "https://food52.com/", "Recipe community and cooking", "Cooking")
add("Bon Appetit", "https://www.bonappetit.com/", "Recipes and food culture", "Cooking")
add("King Arthur Baking", "https://www.kingarthurbaking.com/", "Baking recipes and guides", "Cooking")
add("Smitten Kitchen", "https://smittenkitchen.com/", "Home cooking with great photos", "Cooking")
add("The Kitchn", "https://www.thekitchn.com/", "Kitchen tips and home cooking", "Cooking")
add("Budget Bytes", "https://www.budgetbytes.com/", "Affordable recipes with costs", "Cooking")
add("Minimalist Baker", "https://minimalistbaker.com/", "Simple recipes few ingredients", "Cooking")
add("RecipeTin Eats", "https://www.recipetineats.com/", "Trusted step-by-step recipes", "Cooking")
add("Simply Recipes", "https://www.simplyrecipes.com/", "Family-friendly recipes", "Cooking")
add("Taste of Home", "https://www.tasteofhome.com/", "Home-style cooking community", "Cooking")
add("NYT Cooking", "https://cooking.nytimes.com/", "New York Times recipe collection", "Cooking")
add("Sprue Eats", "https://www.thespruceeats.com/", "Practical cooking how-tos", "Cooking")
add("BBC Good Food", "https://www.bbcgoodfood.com/", "BBC recipes and cooking tips", "Cooking")

# ============ CHESS ============
add("Chess.com", "https://www.chess.com/", "Largest online chess platform", "Chess")
add("Lichess", "https://lichess.org/", "Free open-source chess server", "Chess")
add("Chess24", "https://chess24.com/", "Chess news and videos", "Chess")
add("ChessBase", "https://chessbase.com/", "Chess database and news", "Chess")
add("Chessgames.com", "https://www.chessgames.com/", "Massive chess game database", "Chess")
add("ICCF", "https://www.iccf.com/", "Correspondence Chess Federation", "Chess")
add("US Chess", "https://www.uschess.org/", "US Chess Federation official", "Chess")
add("Chess Tempo", "https://chesstempo.com/", "Chess tactics training", "Chess")
add("FIDE", "https://www.fide.com/", "International Chess Federation", "Chess")
add("365Chess", "https://www.365chess.com/", "Free chess game database", "Chess")
add("Chessable", "https://www.chessable.com/", "Interactive chess courses", "Chess")
add("Listudy", "https://listudy.org/", "Free chess spaced repetition", "Chess")
add("Decode Chess", "https://decodechess.com/", "AI-powered chess analysis", "Chess")
add("ChessPuzzles.net", "https://chesspuzzles.net/", "Free chess puzzle collection", "Chess")
add("ChessVision", "https://chessvision.ai/", "AI chess position analyzer", "Chess")

# ============ CLIMBING ============
add("Mountain Project", "https://www.mountainproject.com/", "Rock climbing routes database", "Climbing")
add("8a.nu", "https://www.8a.nu/", "Climbing scores and community", "Climbing")
add("UK Climbing", "https://www.ukclimbing.com/", "UK climbing news and forums", "Climbing")
add("Climbing Magazine", "https://www.climbing.com/", "Rock climbing gear news", "Climbing")
add("TheCrag", "https://www.thecrag.com/", "Worldwide climbing routes", "Climbing")
add("Sendage", "https://sendage.com/", "Online climbing training log", "Climbing")
add("Rock and Ice", "https://www.rockandice.com/", "Climbing news and features", "Climbing")
add("Gripped Magazine", "https://gripped.com/", "Canadian climbing magazine", "Climbing")
add("TrainingBeta", "https://trainingbeta.com/", "Climbing training podcast", "Climbing")
add("Hard Climbing News", "https://www.hardclimbs.info/", "Hard new routing news", "Climbing")
add("Reddit Climbing", "https://www.reddit.com/r/climbing/", "Climbing community on Reddit", "Climbing")
add("Beta Boys", "https://betaboys.com/", "Climbing coaching plans", "Climbing")
add("Climbing Tech Tips", "https://www.climbingtechtips.com/", "Gear maintenance skills", "Climbing")
add("99Boulders", "https://www.99boulders.com/", "Rock climbing reviews and guides", "Climbing")

# ============ MOTORCYCLES ============
add("RevZilla", "https://www.revzilla.com/", "Motorcycle gear and advice", "Motorcycles")
add("Motorcycle.com", "https://www.motorcycle.com/", "Motorcycle reviews and forums", "Motorcycles")
add("Cycle World", "https://www.cycleworld.com/", "Motorcycle magazine reviews", "Motorcycles")
add("ADV Rider", "https://www.advrider.com/", "Adventure touring community", "Motorcycles")
add("Visordown", "https://www.visordown.com/", "Motorcycle news community", "Motorcycles")
add("MotoGP", "https://www.motogp.com/", "Official MotoGP racing website", "Motorcycles")
add("RideApart", "https://www.rideapart.com/", "Motorcycle lifestyle news", "Motorcycles")
add("MCN", "https://www.motorcyclenews.com/", "UK motorcycle news and reviews", "Motorcycles")
add("WebBikeWorld", "https://www.webbikeworld.com/", "Motorcycle gear reviews", "Motorcycles")
add("Total Motorcycle", "https://www.totalmotorcycle.com/", "Motorcycle buying guides", "Motorcycles")
add("Motorcycle Forum", "https://www.motorcycleforum.com/", "Motorcycle discussion forum", "Motorcycles")
add("Bike EXIF", "https://www.bikeexif.com/", "Custom motorcycle blog", "Motorcycles")
add("Pipe Burn", "https://www.pipeburn.com/", "Custom motorcycle builds", "Motorcycles")
add("Return of the Cafe Racers", "https://www.returnofthecaferacers.com/", "Cafe racer culture", "Motorcycles")

# ============ GENEALOGY ============
add("Ancestry", "https://www.ancestry.com/", "Genealogy research platform", "Genealogy")
add("FamilySearch", "https://www.familysearch.org/", "Free genealogy platform", "Genealogy")
add("MyHeritage", "https://www.myheritage.com/", "DNA and family history", "Genealogy")
add("FindMyPast", "https://www.findmypast.com/", "UK Irish genealogy records", "Genealogy")
add("Geni", "https://www.geni.com/", "Collaborative family tree", "Genealogy")
add("WikiTree", "https://www.wikitree.com/", "Free collaborative family tree", "Genealogy")
add("US National Archives", "https://www.archives.gov/", "US census and records", "Genealogy")
add("RootsWeb", "https://www.rootsweb.com/", "Free genealogy community", "Genealogy")
add("Cyndi's List", "https://www.cyndislist.com/", "Genealogy web directory", "Genealogy")
add("Find a Grave", "https://www.findagrave.com/", "Cemetery records database", "Genealogy")
add("Family Tree Magazine", "https://www.familytreemagazine.com/", "Genealogy research guides", "Genealogy")
add("USGenWeb", "https://www.usgenweb.org/", "Free US genealogy project", "Genealogy")
add("Ellis Island Records", "https://heritage.statueofliberty.org/", "Passenger arrival search", "Genealogy")
add("GenealogyBank", "https://www.genealogybank.com/", "Historical newspaper records", "Genealogy")
add("FamilySearch Wiki", "https://www.familysearch.org/en/wiki/", "Genealogy how-to guides", "Genealogy")
add("Forebears", "https://forebears.io/", "Surname and genealogy database", "Genealogy")

# ============ GARDENING ============
add("RHS", "https://www.rhs.org.uk/", "Royal Horticultural Society guides", "Gardening")
add("Gardeners' World", "https://www.gardenersworld.com/", "UK gardening advice", "Gardening")
add("Dave's Garden", "https://davesgarden.com/", "Gardening community database", "Gardening")
add("Fine Gardening", "https://www.finegardening.com/", "Detailed gardening guides", "Gardening")
add("Old Farmer's Almanac", "https://www.almanac.com/gardening", "Gardening calendar guides", "Gardening")
add("Garden Design", "https://www.gardendesign.com/", "Landscape design ideas", "Gardening")
add("Planet Natural", "https://www.planetnatural.com/", "Organic gardening supplies", "Gardening")
add("Gardenista", "https://www.gardenista.com/", "Garden design sourcing", "Gardening")
add("Permaculture News", "https://www.permaculturenews.org/", "Permaculture articles", "Gardening")
add("Royal Botanic Kew", "https://www.kew.org/", "Plant science resources", "Gardening")
add("Missouri Botanical Garden", "https://www.missouribotanicalgarden.org/", "Plant finder resources", "Gardening")
add("Epic Gardening", "https://www.epicgardening.com/", "Modern gardening tutorials", "Gardening")
add("GrowVeg", "https://www.growveg.com/", "Vegetable garden planner", "Gardening")
add("Gardening Know How", "https://www.gardeningknowhow.com/", "Beginner gardening guides", "Gardening")
add("Royal Botanic Edinburgh", "https://www.rbge.org.uk/", "Botanical garden resources", "Gardening")

# ============ SAILING ============
add("SailWorld", "https://www.sailworld.com/", "Sailing news and regattas", "Sailing")
add("Cruising World", "https://www.cruisingworld.com/", "Cruising sailboat reviews", "Sailing")
add("Sailing Anarchy", "https://sailinganarchy.com/", "Sailing news and satire", "Sailing")
add("SailNet", "https://www.sailnet.com/", "Sailing community forums", "Sailing")
add("Yachting World", "https://www.yachtingworld.com/", "Yachting news and racing", "Sailing")
add("Practical Sailor", "https://www.practical-sailor.com/", "Independent gear reviews", "Sailing")
add("World Sailing", "https://www.sailing.org/", "International sailing federation", "Sailing")
add("BoatUS", "https://www.boatus.com/", "Boat owner resources", "Sailing")
add("Sailing Today", "https://www.sailingtoday.co.uk/", "UK sailing magazine", "Sailing")
add("Latitude 38", "https://www.latitude38.com/", "West Coast sailing magazine", "Sailing")
add("Noonsite", "https://www.noonsite.com/", "Cruising port information", "Sailing")
add("Offshore Sailing", "https://www.offshoresailing.com/", "Sailing school resources", "Sailing")

# ============ SURFING ============
add("Surfline", "https://www.surfline.com/", "Surf forecasts and cams", "Surfing")
add("MagicSeaweed", "https://magicseaweed.com/", "Surf forecasts and guides", "Surfing")
add("World Surf League", "https://www.worldsurfleague.com/", "Pro surfing tour rankings", "Surfing")
add("Surfer Magazine", "https://www.surfer.com/", "Surfing culture photography", "Surfing")
add("Stab Magazine", "https://stabmag.com/", "Surfing creative content", "Surfing")
add("SurferToday", "https://www.surfertoday.com/", "Surfing news and tips", "Surfing")
add("BeachGrit", "https://beachgrit.com/", "Humorous surf commentary", "Surfing")
add("SwellInfo", "https://www.swellinfo.com/", "Surf forecasts and buoys", "Surfing")
add("Carve Surfing", "https://carvesurf.com/", "European surf magazine", "Surfing")
add("Surf Travel", "https://www.surftravelcompany.com/", "Surf trip destination guides", "Surfing")
add("Surfd", "https://surfd.com/", "Surfing photography videos", "Surfing")
add("Inertia", "https://www.theinertia.com/", "Surf lifestyle and news", "Surfing")

# ============ HIKING ============
add("AllTrails", "https://www.alltrails.com/", "Hiking trail guide database", "Hiking")
add("REI Hiking", "https://www.rei.com/learn/hiking.html", "Hiking expert advice", "Hiking")
add("The Hiking Life", "https://thehikinglife.com/", "Long-distance hiking tips", "Hiking")
add("SectionHiker", "https://sectionhiker.com/", "Lightweight backpacking gear", "Hiking")
add("SummitPost", "https://www.summitpost.org/", "Climbing hiking routes", "Hiking")
add("Walkopedia", "https://walkopedia.net/", "World's best hiking walks", "Hiking")
add("The Trek", "https://thetrek.co/", "Thru-hiking stories community", "Hiking")
add("Hiking Project", "https://www.hikingproject.com/", "Curated hiking trails", "Hiking")
add("Backpacker Magazine", "https://www.backpacker.com/", "Backpacking gear reviews", "Hiking")
add("American Hiking", "https://americanhiking.org/", "Hiking advocacy conservation", "Hiking")
add("The Outbound", "https://www.theoutbound.com/", "Outdoor adventure community", "Hiking")
add("Modern Hiker", "https://modernhiker.com/", "Southern CA hiking guides", "Hiking")
add("Outdoor Vital", "https://outdoorvital.com/", "Hiking camping gear reviews", "Hiking")

# ============ WOODWORKING ============
add("Wood Magazine", "https://www.woodmagazine.com/", "Woodworking plans techniques", "Woodworking")
add("Fine Woodworking", "https://www.finewoodworking.com/", "Premium woodworking magazine", "Woodworking")
add("Lost Art Press", "https://lostartpress.com/", "Traditional woodworking books", "Woodworking")
add("WWGOA", "https://www.wwgoa.com/", "Video tutorials and plans", "Woodworking")
add("Ana White", "https://www.ana-white.com/", "DIY furniture for beginners", "Woodworking")
add("Woodsmith", "https://www.woodsmith.com/", "Woodworking plans shop tips", "Woodworking")
add("Popular Woodworking", "https://www.popularwoodworking.com/", "Woodworking magazine community", "Woodworking")
add("DIY Woodworking", "https://www.diywoodworking.com/", "Woodworking project ideas", "Woodworking")
add("Shanty 2 Chic", "https://www.shanty2chic.com/", "DIY furniture plans decor", "Woodworking")
add("Woodwork Boss", "https://www.woodworkboss.com/", "Woodworking guides tutorials", "Woodworking")
add("Sawdust Girl", "https://sawdustgirl.com/", "DIY furniture building blog", "Woodworking")
add("LumberJocks", "https://www.lumberjocks.com/", "Active woodworking community", "Woodworking")

# ============ BEER BREWING ============
add("Brewers Association", "https://www.brewersassociation.org/", "Homebrew resources", "Beer Brewing")
add("BeerAdvocate", "https://www.beeradvocate.com/", "Beer reviews community", "Beer Brewing")
add("RateBeer", "https://www.ratebeer.com/", "Beer ratings and info", "Beer Brewing")
add("HomeBrewTalk", "https://www.homebrewtalk.com/", "Homebrewing forum community", "Beer Brewing")
add("Northern Brewer", "https://www.northernbrewer.com/", "Homebrew supplies recipes", "Beer Brewing")
add("AHA", "https://www.homebrewersassociation.org/", "Homebrewing education", "Beer Brewing")
add("Brewer's Friend", "https://www.brewersfriend.com/", "Brewing calculators recipes", "Beer Brewing")
add("Craft Beer & Brewing", "https://beerandbrewing.com/", "Brewing techniques news", "Beer Brewing")
add("MoreBeer", "https://www.morebeer.com/", "Homebrew supplies equipment", "Beer Brewing")
add("Brew United", "https://brewunited.com/", "Recipe management platform", "Beer Brewing")
add("BrewDog Blog", "https://www.brewdog.com/blog", "Craft brewing blog", "Beer Brewing")
add("Craft Beer", "https://www.craftbeer.com/", "Craft beer styles guides", "Beer Brewing")

# ============ WINE ============
add("Wine Spectator", "https://www.winespectator.com/", "Wine ratings buying guides", "Wine")
add("Decanter", "https://www.decanter.com/", "Fine wine expert reviews", "Wine")
add("Wine Enthusiast", "https://www.wineenthusiast.com/", "Wine ratings lifestyle", "Wine")
add("Vivino", "https://www.vivino.com/", "Wine database prices ratings", "Wine")
add("Wine Folly", "https://winefolly.com/", "Wine education visual guides", "Wine")
add("CellarTracker", "https://www.cellartracker.com/", "Wine cellar management", "Wine")
add("Jancis Robinson", "https://www.jancisrobinson.com/", "Wine expert commentary", "Wine")
add("Wine Searcher", "https://www.wine-searcher.com/", "Wine prices search", "Wine")
add("Wine Cellar Insider", "https://www.thewinecellarinsider.com/", "Bordeaux wine knowledge", "Wine")
add("GuildSomm", "https://www.guildsomm.com/", "Sommelier study materials", "Wine")
add("Drinks Business", "https://www.thedrinksbusiness.com/", "Wine spirits industry news", "Wine")

# ============ HOME AUTOMATION ============
add("Home Assistant", "https://www.home-assistant.io/", "Open-source home automation", "Home Automation")
add("OpenHAB", "https://www.openhab.org/", "Open-source home automation", "Home Automation")
add("ESPHome", "https://esphome.io/", "ESP32/8266 automation firmware", "Home Automation")
add("Tasmota", "https://tasmota.github.io/", "ESP8266 open firmware", "Home Automation")
add("Zigbee2MQTT", "https://www.zigbee2mqtt.io/", "Zigbee to MQTT bridge", "Home Automation")
add("Mozilla WebThings", "https://webthings.io/", "Web of Things gateway", "Home Automation")
add("SmartThings", "https://www.smartthings.com/", "Samsung smart home", "Home Automation")
add("Hubitat", "https://hubitat.com/", "Local home automation hub", "Home Automation")
add("OpenRemote", "https://openremote.io/", "Open-source IoT management", "Home Automation")
add("IoBroker", "https://www.iobroker.net/", "Home automation platform", "Home Automation")
add("Homebridge", "https://homebridge.io/", "HomeKit for non-HomeKit", "Home Automation")
add("Node-RED", "https://nodered.org/", "Flow-based IoT automation", "Home Automation")
add("WLED", "https://kno.wled.ge/", "ESP8266 LED strip controller", "Home Automation")

# ============ PHOTOGRAPHY ============
add("500px", "https://500px.com/", "Photography community marketplace", "Photography")
add("Flickr", "https://www.flickr.com/", "Photo sharing community", "Photography")
add("Unsplash", "https://unsplash.com/", "Free high-res stock photos", "Photography")
add("Pexels", "https://www.pexels.com/", "Free stock photos videos", "Photography")
add("DPReview", "https://www.dpreview.com/", "Digital camera reviews", "Photography")
add("PetaPixel", "https://petapixel.com/", "Photography news gear", "Photography")
add("Photography Life", "https://photographylife.com/", "Photo tutorials reviews", "Photography")
add("Luminous Landscape", "https://luminous-landscape.com/", "Landscape photography tutorials", "Photography")
add("1x.com", "https://1x.com/", "Curated fine art photography", "Photography")
add("Cambridge in Colour", "https://www.cambridgeincolour.com/", "Digital photography tutorials", "Photography")
add("Phlearn", "https://phlearn.com/", "Photoshop photography tutorials", "Photography")
add("ViewBug", "https://www.viewbug.com/", "Photo contests community", "Photography")
add("Photocrowd", "https://www.photocrowd.com/", "Photography competitions", "Photography")

# ============ YOGA & MEDITATION ============
add("Yoga Journal", "https://www.yogajournal.com/", "Yoga poses and wellness", "Yoga & Meditation")
add("Yoga with Adriene", "https://yogawithadriene.com/", "Free yoga for all levels", "Yoga & Meditation")
add("Headspace", "https://www.headspace.com/", "Meditation mindfulness app", "Yoga & Meditation")
add("Calm", "https://www.calm.com/", "Meditation sleep app", "Yoga & Meditation")
add("Insight Timer", "https://insighttimer.com/", "Free guided meditation", "Yoga & Meditation")
add("DoYogaWithMe", "https://www.doyogawithme.com/", "Free online yoga classes", "Yoga & Meditation")
add("Yoga International", "https://yogainternational.com/", "Online yoga classes", "Yoga & Meditation")
add("Ekhart Yoga", "https://www.ekhartyoga.com/", "Online yoga tutorials", "Yoga & Meditation")
add("Mindful.org", "https://www.mindful.org/", "Mindfulness resources", "Yoga & Meditation")
add("Tara Brach", "https://www.tarabrach.com/", "Meditation talks and practice", "Yoga & Meditation")
add("UCLA Mindful", "https://www.uclahealth.org/mindful/", "Free guided meditation", "Yoga & Meditation")
add("Plum Village", "https://plumvillage.org/", "Thich Nhat Hanh mindfulness", "Yoga & Meditation")
add("Gaia", "https://www.gaia.com/", "Yoga spirituality videos", "Yoga & Meditation")
add("Fitness Blender Yoga", "https://www.fitnessblender.com/", "Free yoga workout videos", "Yoga & Meditation")

# ============ MARTIAL ARTS ============
add("BJJ Heroes", "https://www.bjjheroes.com/", "BJJ fighter database", "Martial Arts")
add("Boxing Scene", "https://www.boxingscene.com/", "Boxing news results", "Martial Arts")
add("MMA Junkie", "https://mmajunkie.com/", "MMA news coverage", "Martial Arts")
add("Sherdog", "https://www.sherdog.com/", "MMA fighter database", "Martial Arts")
add("Kungfu Magazine", "https://www.kungfumagazine.com/", "Kung fu culture", "Martial Arts")
add("Aikido Journal", "https://www.aikidojournal.com/", "Aikido techniques history", "Martial Arts")
add("Bullshido", "https://www.bullshido.net/", "Martial arts authenticity", "Martial Arts")
add("Fight Matrix", "https://www.fightmatrix.com/", "MMA rankings data", "Martial Arts")
add("Krav Maga Worldwide", "https://www.kravmaga.com/", "Krav Maga training", "Martial Arts")
add("Judo World", "https://judoworld.org/", "Judo news rankings", "Martial Arts")
add("Taekwondo Data", "https://www.taekwondodata.com/", "Taekwondo competitors", "Martial Arts")
add("Dojo Directory", "https://dojodirectory.com/", "Worldwide martial arts schools", "Martial Arts")
add("My MMA News", "https://www.mymmanews.com/", "MMA news analysis", "Martial Arts")

# ============ DIGITAL ART ============
add("Procreate", "https://procreate.art/", "Digital illustration for iPad", "Digital Art")
add("Krita", "https://krita.org/", "Free open-source digital painting", "Digital Art")
add("Clip Studio Paint", "https://www.clipstudio.net/", "Manga and comic creation", "Digital Art")
add("DeviantArt", "https://www.deviantart.com/", "Digital art portfolio community", "Digital Art")
add("ArtStation", "https://www.artstation.com/", "Pro digital art portfolio", "Digital Art")
add("CGSociety", "https://www.cgsociety.org/", "CG artists community", "Digital Art")
add("Drawabox", "https://drawabox.com/", "Free drawing fundamentals", "Digital Art")
add("Pixiv", "https://www.pixiv.net/", "Japanese illustration community", "Digital Art")
add("Sketchfab", "https://sketchfab.com/", "3D model publishing", "Digital Art")
add("Ctrl+Paint", "https://www.ctrlpaint.com/", "Digital painting tutorials", "Digital Art")
add("Concept Art World", "https://conceptartworld.com/", "Concept art inspiration", "Digital Art")
add("Infinite Painter", "https://www.infinitestudio.art/", "Digital painting mobile", "Digital Art")
add("ArtRage", "https://www.artrage.com/", "Realistic painting simulation", "Digital Art")
add("Affinity Designer", "https://affinity.serif.com/designer/", "Vector graphic design", "Digital Art")
add("Pixologic ZBrush", "https://pixologic.com/", "Digital sculpting software", "Digital Art")
add("PaintTool SAI", "https://www.systemax.jp/en/sai/", "Popular digital painting", "Digital Art")
add("MediBang Paint", "https://medibangpaint.com/", "Free manga illustration", "Digital Art")

# ============ DATA SCIENCE ============
add("Kaggle", "https://www.kaggle.com/", "ML competitions datasets", "Data Science")
add("Towards Data Science", "https://towardsdatascience.com/", "Data science articles", "Data Science")
add("KDnuggets", "https://www.kdnuggets.com/", "Data science analytics news", "Data Science")
add("DataCamp", "https://www.datacamp.com/", "Interactive data science courses", "Data Science")
add("Analytics Vidhya", "https://www.analyticsvidhya.com/", "Data science learning", "Data Science")
add("UCI ML Repo", "https://archive.ics.uci.edu/", "ML benchmark datasets", "Data Science")
add("Papers With Code", "https://paperswithcode.com/", "ML papers implementations", "Data Science")
add("Hugging Face", "https://huggingface.co/", "ML model hub community", "Data Science")
add("TensorFlow", "https://www.tensorflow.org/", "Google ML platform", "Data Science")
add("PyTorch", "https://pytorch.org/", "Open-source ML framework", "Data Science")
add("Jupyter", "https://jupyter.org/", "Interactive computing notebook", "Data Science")
add("Fast.ai", "https://www.fast.ai/", "Practical deep learning", "Data Science")
add("StatQuest", "https://statquest.org/", "Statistics ML video tutorials", "Data Science")
add("Scikit-learn", "https://scikit-learn.org/", "Python ML library", "Data Science")
add("Keras", "https://keras.io/", "Deep learning Python API", "Data Science")

# ============ TYPOGRAPHY ============
add("Google Fonts", "https://fonts.google.com/", "Free open-source fonts", "Typography")
add("Font Squirrel", "https://www.fontsquirrel.com/", "Free commercial-use fonts", "Typography")
add("DaFont", "https://www.dafont.com/", "Large free font archive", "Typography")
add("MyFonts", "https://www.myfonts.com/", "Commercial font marketplace", "Typography")
add("FontSpace", "https://www.fontspace.com/", "Free font downloads community", "Typography")
add("Typewolf", "https://www.typewolf.com/", "Typography inspiration", "Typography")
add("Fonts In Use", "https://fontsinuse.com/", "Real-world typography reference", "Typography")
add("I Love Typography", "https://ilovetypography.com/", "Typography blog news", "Typography")
add("Typographica", "https://typographica.org/", "Typeface reviews", "Typography")
add("FontLab", "https://www.fontlab.com/", "Font editing software", "Typography")
add("FontForge", "https://fontforge.org/", "Free open-source font editor", "Typography")
add("League of Moveable Type", "https://www.theleagueofmoveabletype.com/", "Open-source foundry", "Typography")
add("Identifont", "https://www.identifont.com/", "Font identification service", "Typography")
add("TypeTogether", "https://www.type-together.com/", "Award-winning type foundry", "Typography")
add("Glyphs", "https://glyphsapp.com/", "Professional font editor Mac", "Typography")
add("Beautiful Web Type", "https://beautifulwebtype.com/", "Curated open-source typefaces", "Typography")

# ============ CYCLING ============
add("BikeRadar", "https://www.bikeradar.com/", "Bike reviews buying guides", "Cycling")
add("Cycling Weekly", "https://www.cyclingweekly.com/", "UK cycling news", "Cycling")
add("PinkBike", "https://www.pinkbike.com/", "Mountain biking community", "Cycling")
add("GCN", "https://www.globalcyclingnetwork.com/", "Cycling training videos", "Cycling")
add("CyclingTips", "https://cyclingtips.com/", "Cycling performance tech", "Cycling")
add("VeloNews", "https://www.velonews.com/", "Competitive cycling news", "Cycling")
add("ProCyclingStats", "https://www.procyclingstats.com/", "Pro cycling race database", "Cycling")
add("Sheldon Brown", "https://sheldonbrown.com/", "Bicycle technical info", "Cycling")
add("Bike Forums", "https://www.bikeforums.net/", "Cycling forum community", "Cycling")
add("MTB News", "https://www.mtb-news.de/", "German mountain bike news", "Cycling")
add("Road Bike Action", "https://www.roadbikeaction.com/", "Road cycling gear reviews", "Cycling")
add("Bicycle Network", "https://www.bicyclenetwork.com.au/", "Aus cycling advocacy", "Cycling")

# ============ MYCOLOGY ============
add("Mushroom Expert", "https://www.mushroomexpert.com/", "Mushroom ID cultivation", "Mycology")
add("Shroomery", "https://www.shroomery.org/", "Mushroom cultivation community", "Mycology")
add("iNaturalist Fungi", "https://www.inaturalist.org/guides/fungi", "Fungi observation database", "Mycology")
add("Fungi Perfecti", "https://fungi.com/", "Paul Stamets mushroom resources", "Mycology")
add("NAMA", "https://namyco.org/", "North American mycology association", "Mycology")
add("First Nature Fungi", "https://www.first-nature.com/fungi/", "UK fungi identification", "Mycology")
add("MycoBank", "https://www.mycobank.org/", "Fungal species database", "Mycology")
add("Index Fungorum", "https://www.indexfungorum.org/", "Global fungal species names", "Mycology")
add("Mushroom World", "https://www.mushroom.world/", "Mushroom ID and recipes", "Mycology")
add("Mycelium Running", "https://myceliumrunning.com/", "Permaculture mushrooms", "Mycology")
add("iNaturalist Fungi", "https://www.inaturalist.org/projects/fungi", "Citizen science fungi", "Mycology")

# ============ FORAGING ============
add("Wild Food UK", "https://www.wildfooduk.com/", "Foraging guides ID", "Foraging")
add("Eat The Weeds", "https://www.eattheweeds.com/", "Edible plant ID foraging", "Foraging")
add("Forager Chef", "https://foragerchef.com/", "Wild food foraging cooking", "Foraging")
add("Wild Edible", "https://www.wildedible.com/", "Wild edible plant database", "Foraging")
add("Falling Fruit", "https://fallingfruit.org/", "Urban foraging map", "Foraging")
add("PFAF", "https://pfaf.org/", "Edible medicinal plant database", "Foraging")
add("Wildman Steve Brill", "https://wildmanstevebrill.com/", "Foraging tours education", "Foraging")
add("Edible Wild Food", "https://www.ediblewildfood.com/", "Wild food recipes foraging", "Foraging")
add("Honest Food", "https://honest-food.net/", "Wild food cooking hunting", "Foraging")
add("Foraged Foodie", "https://foragedfoodie.blogspot.com/", "Foraging recipes preservation", "Foraging")

# ============ VINYL RECORDS ============
add("Discogs", "https://www.discogs.com/", "Music database vinyl marketplace", "Vinyl Records")
add("Vinyl Me Please", "https://www.vinylmeplease.com/", "Curated vinyl subscription", "Vinyl Records")
add("Acoustic Sounds", "https://www.acousticsounds.com/", "Audiophile vinyl gear", "Vinyl Records")
add("Turntable Lab", "https://www.turntablelab.com/", "Turntables DJ equipment", "Vinyl Records")
add("Rough Trade", "https://roughtrade.com/", "Independent record store", "Vinyl Records")
add("Amoeba Music", "https://www.amoeba.com/", "Legendary record store", "Vinyl Records")
add("Record Collector Mag", "https://recordcollectormag.com/", "Record collecting magazine", "Vinyl Records")
add("Vinyl Guru", "https://www.vinylguru.com/", "Record care accessories", "Vinyl Records")
add("Bleep", "https://bleep.com/", "Electronic music vinyl", "Vinyl Records")
add("Music Direct", "https://www.musicdirect.com/", "Audiophile records", "Vinyl Records")

# ============ PODCASTING ============
add("Anchor", "https://anchor.fm/", "Free podcast hosting Spotify", "Podcasting")
add("Libsyn", "https://www.libsyn.com/", "Professional podcast hosting", "Podcasting")
add("Buzzsprout", "https://www.buzzsprout.com/", "Easy podcast hosting", "Podcasting")
add("Podbean", "https://www.podbean.com/", "Podcast hosting monetization", "Podcasting")
add("Transistor", "https://transistor.fm/", "Podcast hosting business", "Podcasting")
add("Alitu", "https://alitu.com/", "All-in-one podcast production", "Podcasting")
add("Auphonic", "https://auphonic.com/", "Automatic audio leveling", "Podcasting")
add("Descript", "https://www.descript.com/", "AI audio video editor", "Podcasting")
add("Riverside.fm", "https://riverside.fm/", "Remote podcast recording", "Podcasting")
add("Zencastr", "https://zencastr.com/", "Remote podcast recording", "Podcasting")
add("Podcast Insights", "https://www.podcastinsights.com/", "Podcasting statistics guides", "Podcasting")
add("Podcast Host", "https://thepodcasthost.com/", "Podcast planning growth", "Podcasting")
add("Headliner", "https://www.headliner.app/", "Podcast video clips", "Podcasting")

# ============ ANIMATION ============
add("Animation Magazine", "https://www.animationmagazine.net/", "Animation industry news", "Animation")
add("Cartoon Brew", "https://www.cartoonbrew.com/", "Animation news commentary", "Animation")
add("Blender Studio", "https://cloud.blender.org/", "Blender open movies training", "Animation")
add("Toon Boom", "https://www.toonboom.com/", "Professional animation software", "Animation")
add("Animation Mentor", "https://www.animationmentor.com/", "Online animation school", "Animation")
add("11 Second Club", "https://www.11secondclub.com/", "Monthly animation competition", "Animation")
add("Newgrounds Animation", "https://www.newgrounds.com/animation", "Animation community", "Animation")
add("Synfig Studio", "https://www.synfig.org/", "Free 2D animation software", "Animation")
add("OpenToonz", "https://opentoonz.github.io/", "Free 2D animation software", "Animation")
add("Stop Motion Animation", "https://www.stopmotionanimation.com/", "Stop motion community", "Animation")
add("Animator Island", "https://www.animatorisland.com/", "Animation tutorials", "Animation")
add("TVPaint", "https://www.tvpaint.com/", "2D traditional animation", "Animation")

# ============ CALLIGRAPHY ============
add("Postman's Knock", "https://thepostmansknock.com/", "Calligraphy tutorials", "Calligraphy")
add("IAMPETH", "https://iampeth.com/", "International penmanship association", "Calligraphy")
add("Penna Volans", "https://www.pennavolans.com/", "Calligraphy tutorials", "Calligraphy")
add("Flourish Forum", "https://theflourishforum.com/", "Calligraphy lettering community", "Calligraphy")
add("Reddit Calligraphy", "https://www.reddit.com/r/Calligraphy/", "Calligraphy community", "Calligraphy")
add("Paper & Ink Arts", "https://www.paperinkarts.com/", "Calligraphy supplies nibs", "Calligraphy")
add("JetPens", "https://www.jetpens.com/", "Japanese pen stationery", "Calligraphy")
add("Goulet Pens", "https://www.gouletpens.com/", "Fountain pens ink retailer", "Calligraphy")
add("Loops & Tails", "https://loopsandtails.com/", "Calligraphy practice sheets", "Calligraphy")
add("Calligraphish", "https://www.calligraphish.com/", "Modern calligraphy worksheets", "Calligraphy")

# ============ PARANORMAL & UFO ============
add("MUFON", "https://www.mufon.com/", "Mutual UFO Network", "Paranormal & UFO")
add("NUFORC", "https://nuforc.org/", "National UFO Reporting Center", "Paranormal & UFO")
add("Coast to Coast AM", "https://www.coasttocoastam.com/", "Paranormal radio show", "Paranormal & UFO")
add("The Debrief", "https://thedebrief.org/", "UFO science news", "Paranormal & UFO")
add("Above Top Secret", "https://www.abovetopsecret.com/", "Conspiracy forum", "Paranormal & UFO")
add("Fortean Times", "https://forteantimes.com/", "Strange phenomena news", "Paranormal & UFO")
add("Cryptozoology Museum", "https://cryptozoologymuseum.com/", "Cryptozoology museum", "Paranormal & UFO")
add("The Anomalist", "https://www.anomalist.com/", "Paranormal unusual news", "Paranormal & UFO")
add("Ghost Hunters", "https://ghosthunters.com/", "Ghost hunting resources", "Paranormal & UFO")
add("Fortean Zoology", "https://forteanzoology.com/", "Cryptozoology research", "Paranormal & UFO")
add("Paranormal Society", "https://www.paranormalsociety.org/", "Scientific paranormal investigation", "Paranormal & UFO")

# ============ METALWORKING ============
add("The Fabricator", "https://www.thefabricator.com/", "Metal fabrication news", "Metalworking")
add("Practical Machinist", "https://www.practicalmachinist.com/", "Machining forum community", "Metalworking")
add("Welding Tips Tricks", "https://www.weldingtipsandtricks.com/", "Welding tutorials", "Metalworking")
add("Miller Welds", "https://www.millerwelds.com/", "Welding equipment resources", "Metalworking")
add("Lincoln Electric", "https://www.lincolnelectric.com/", "Welding products education", "Metalworking")
add("Hobby Machinist", "https://www.hobby-machinist.com/", "Hobbyist machining forum", "Metalworking")
add("Home Model Engine", "https://www.homemodelenginemachinist.com/", "Model engine machining", "Metalworking")
add("McMaster-Carr", "https://www.mcmaster.com/", "Industrial hardware supply", "Metalworking")
add("Artisan Foundry", "https://www.artisanfoundry.com/", "Bronze casting sculpture", "Metalworking")
add("The Welding Web", "https://www.theweldingweb.com/", "Welding community forum", "Metalworking")

# ============ LEATHERWORKING ============
add("Leatherworker.net", "https://leatherworker.net/", "Leatherworking community", "Leatherworking")
add("Tandy Leather", "https://www.tandyleather.com/", "Leather craft supplies", "Leatherworking")
add("Weaver Leather", "https://www.weaverleather.com/", "Leather crafting supplies", "Leatherworking")
add("Springfield Leather", "https://www.springfieldleather.com/", "Leathercraft supplies", "Leatherworking")
add("Leather Hub", "https://www.leatherhub.com/", "Leather supply tools", "Leatherworking")
add("Buckleguy", "https://www.buckleguy.com/", "Leathercraft hardware", "Leatherworking")
add("Lonsdale Leather", "https://www.lonsdaleleather.co.uk/", "UK leathercraft supplier", "Leatherworking")
add("Nigel Armitage", "https://www.youtube.com/user/nigelarmitage", "Leather craft tutorials", "Leatherworking")
add("Armitage Leather", "https://www.armitageleather.com/", "High-end leather tutorials", "Leatherworking")

# ============ JEWELRY MAKING ============
add("Rio Grande", "https://www.riogrande.com/", "Jewelry tools supplies", "Jewelry Making")
add("Fire Mountain Gems", "https://www.firemountaingems.com/", "Beads jewelry supplies", "Jewelry Making")
add("Ganoksin", "https://www.ganoksin.com/", "Jewelry making community", "Jewelry Making")
add("Art Jewelry Magazine", "https://www.artjewelrymag.com/", "Contemporary jewelry art", "Jewelry Making")
add("Jewelry Making Daily", "https://www.jewelrymakingdaily.com/", "Jewelry tutorials projects", "Jewelry Making")
add("International Gem Society", "https://www.gemsociety.org/", "Gemstone education", "Jewelry Making")
add("Stuller", "https://www.stuller.com/", "Fine jewelry findings", "Jewelry Making")
add("Metal Clay Academy", "https://www.metalclayacademy.com/", "Precious metal clay", "Jewelry Making")
add("Etsy Jewelry", "https://www.etsy.com/c/jewelry", "Handmade jewelry marketplace", "Jewelry Making")
add("Beads Direct", "https://www.beadsdirect.co.uk/", "UK bead supply", "Jewelry Making")

# ============ GEOCACHING ============
add("Geocaching.com", "https://www.geocaching.com/", "Official geocaching community", "Geocaching")
add("OpenCaching", "https://www.opencaching.com/", "Open geocaching database", "Geocaching")
add("Cacher", "https://www.cacher.app/", "Geocaching app community", "Geocaching")
add("GeoHashing", "https://geohashing.site/", "GeoHashing community", "Geocaching")
add("Geocaching Australia", "https://geocaching.com.au/", "Australian geocaching", "Geocaching")
add("Geocaching Toolbox", "https://www.geocachingtoolbox.com/", "Geocaching puzzle tools", "Geocaching")
add("Cachly", "https://www.cachly.com/", "iOS geocaching app", "Geocaching")
add("GeoCheck", "https://geocheck.org/", "Geocaching checker service", "Geocaching")

# ============ AMATEUR RADIO ============
add("ARRL", "https://www.arrl.org/", "Ham radio resources", "Amateur Radio")
add("QRZ", "https://www.qrz.com/", "Ham radio callsign database", "Amateur Radio")
add("DX Watch", "https://dxwatch.com/", "Real-time DX spotting", "Amateur Radio")
add("Echolink", "https://www.echolink.org/", "Ham radio over internet", "Amateur Radio")
add("RepeaterBook", "https://repeaterbook.com/", "Ham radio repeater database", "Amateur Radio")
add("WSJT-X", "https://www.physics.princeton.edu/pulsar/k1jt/wsjtx.html", "Weak signal digital", "Amateur Radio")
add("SatNOGS", "https://satnogs.org/", "Satellite ground station", "Amateur Radio")
add("AMSAT", "https://www.amsat.org/", "Amateur satellite", "Amateur Radio")
add("HamStudy", "https://hamstudy.org/", "Ham radio exam study", "Amateur Radio")
add("DXZone", "https://www.dxzone.com/", "Ham radio resources", "Amateur Radio")

# ============ FISHING ============
add("Take Me Fishing", "https://www.takemefishing.org/", "Fishing species guide", "Fishing")
add("Field & Stream", "https://www.fieldandstream.com/fishing/", "Fishing how-to guides", "Fishing")
add("Bass Resource", "https://www.bassresource.com/", "Bass fishing techniques", "Fishing")
add("Fishbrain", "https://fishbrain.com/", "Social fishing app", "Fishing")
add("In-Fisherman", "https://www.in-fisherman.com/", "Fishing strategies tactics", "Fishing")
add("Fly Fisherman", "https://www.flyfisherman.com/", "Fly fishing techniques", "Fishing")
add("Sport Fishing Mag", "https://www.sportfishingmag.com/", "Offshore big game fishing", "Fishing")
add("Kayak Angler", "https://kayakangler.com/", "Kayak fishing community", "Fishing")
add("TackleTour", "https://www.tackletour.com/", "Fishing tackle reviews", "Fishing")

# ============ ARCHERY ============
add("World Archery", "https://worldarchery.sport/", "International archery", "Archery")
add("Archery Talk", "https://www.archerytalk.com/", "Largest archery forum", "Archery")
add("Lancaster Archery", "https://www.lancasterarchery.com/", "Archery retailer blog", "Archery")
add("Archery 360", "https://www.archery360.com/", "Archery lifestyle tips", "Archery")
add("USA Archery", "https://www.usarchery.org/", "National archery body", "Archery")
add("Bow International", "https://www.bow-international.com/", "Archery magazine news", "Archery")
add("Archery GB", "https://www.archerygb.org/", "UK archery organization", "Archery")

# ============ MINIATURE PAINTING ============
add("Games Workshop", "https://www.games-workshop.com/", "Warhammer miniatures wargames", "Miniature Painting")
add("Citadel Colour", "https://citadelcolour.com/", "Official Warhammer painting", "Miniature Painting")
add("CoolMiniOrNot", "https://www.coolminiornot.com/", "Miniature painting gallery", "Miniature Painting")
add("DakkaDakka", "https://www.dakkadakka.com/", "Warhammer tactics forum", "Miniature Painting")
add("Putty and Paint", "https://www.puttyandpaint.com/", "Miniature competition gallery", "Miniature Painting")
add("Warhammer Community", "https://www.warhammer-community.com/", "Official Warhammer news", "Miniature Painting")
add("Reaper Miniatures", "https://www.reapermini.com/", "Fantasy minis manufacturer", "Miniature Painting")
add("BattleScribe", "https://battlescribe.net/", "Warhammer army builder", "Miniature Painting")
add("Wargames Illustrated", "https://www.wargamesillustrated.net/", "Wargaming magazine", "Miniature Painting")

# ============ ESPORTS ============
add("Dot Esports", "https://dotesports.com/", "Esports news analysis", "Esports")
add("HLTV", "https://www.hltv.org/", "CS esports coverage", "Esports")
add("Liquipedia", "https://liquipedia.net/", "Esports wiki by game", "Esports")
add("Esports Earnings", "https://www.esportsearnings.com/", "Prize money database", "Esports")
add("Esports Insider", "https://esportsinsider.com/", "Esports business news", "Esports")
add("GosuGamers", "https://www.gosugamers.net/", "Esports tournaments news", "Esports")
add("Esports Charts", "https://escharts.com/", "Viewership statistics", "Esports")
add("FACEIT", "https://www.faceit.com/", "Competitive gaming platform", "Esports")

# ============ SCUBA DIVING ============
add("PADI", "https://www.padi.com/", "Professional diving association", "Scuba Diving")
add("SSI", "https://www.divessi.com/", "Scuba certification agency", "Scuba Diving")
add("ScubaBoard", "https://www.scubaboard.com/", "Diving forum community", "Scuba Diving")
add("DeeperBlue", "https://www.deeperblue.com/", "Freediving scuba news", "Scuba Diving")
add("Scuba Diving Mag", "https://www.scubadiving.com/", "Diving magazine reviews", "Scuba Diving")
add("Dive Magazine", "https://www.divemagazine.com/", "UK diving magazine", "Scuba Diving")
add("X-Ray Mag", "https://xray-mag.com/", "Digital diving magazine", "Scuba Diving")
add("DivePhotoGuide", "https://www.divephotoguide.com/", "Underwater photography", "Scuba Diving")
add("UW Photography Guide", "https://www.uwphotographyguide.com/", "Underwater photo tutorials", "Scuba Diving")
add("DiveIn", "https://www.divein.com/", "Diving news gear reviews", "Scuba Diving")

# ============ GOLF ============
add("PGA Tour", "https://www.pgatour.com/", "Pro golf tour official", "Golf")
add("Golf Digest", "https://www.golfdigest.com/", "Golf instruction news", "Golf")
add("Golf Magazine", "https://www.golf.com/", "Golf news gear reviews", "Golf")
add("GolfWRX", "https://www.golfwrx.com/", "Golf equipment forum", "Golf")
add("MyGolfSpy", "https://mygolfspy.com/", "Independent golf testing", "Golf")
add("USGA", "https://www.usga.org/", "US Golf Association", "Golf")
add("Golf Monthly", "https://www.golf-monthly.co.uk/", "UK golf magazine", "Golf")
add("GolfNow", "https://www.golfnow.com/", "Tee time booking", "Golf")
add("The Sand Trap", "https://thesandtrap.com/", "Golf instruction community", "Golf")
add("GolfLink", "https://www.golflink.com/", "Course directory reviews", "Golf")
add("R&A", "https://www.randa.org/", "Golf rules governing", "Golf")

# ============ SHORTWAVE LISTENING ============
add("SDRplay", "https://www.sdrplay.com/", "Software defined radio receivers", "Shortwave Listening")
add("RTL-SDR Blog", "https://www.rtl-sdr.com/", "RTL-SDR radio tutorials", "Shortwave Listening")
add("Number Stations", "https://www.numbers-stations.com/", "Number stations database", "Shortwave Listening")
add("GNURadio", "https://www.gnuradio.org/", "Open-source SDR toolkit", "Shortwave Listening")
add("GlobalTuners", "https://www.globaltuners.com/", "Remote SDR network", "Shortwave Listening")
add("WebSDR", "https://www.websdr.org/", "Online SDR directory", "Shortwave Listening")
add("KiwiSDR", "https://kiwisdr.com/", "Open-source SDR project", "Shortwave Listening")
add("SWLing Post", "https://swling.com/", "Shortwave listening news", "Shortwave Listening")
add("SigID Wiki", "https://www.sigidwiki.com/", "Signal identification guide", "Shortwave Listening")
add("Eibi Bumph", "https://eibispace.de/", "Shortwave schedules", "Shortwave Listening")

# ============ MAGIC & ILLUSION ============
add("Penguin Magic", "https://www.penguinmagic.com/", "Magic trick retailer", "Magic & Illusion")
add("Theory11", "https://www.theory11.com/", "Playing cards magic", "Magic & Illusion")
add("Vanishing Inc", "https://www.vanishingincmagic.com/", "Magic shop lectures", "Magic & Illusion")
add("Ellusionist", "https://www.ellusionist.com/", "Card magic mentalism", "Magic & Illusion")
add("Magic Cafe", "https://www.themagiccafe.com/", "Magic forum community", "Magic & Illusion")
add("IBM", "https://www.magician.org/", "Brotherhood of Magicians", "Magic & Illusion")
add("Conjuring Arts", "https://conjuringarts.org/", "Magic research rare books", "Magic & Illusion")
add("Dan and Dave", "https://www.dananddave.com/", "Playing cards cardistry", "Magic & Illusion")

# ============ KNIFE MAKING ============
add("Blade Forums", "https://www.bladeforums.com/", "Knife community marketplace", "Knife Making")
add("Knife Magazine", "https://knifemagazine.com/", "Knife industry news", "Knife Making")
add("Arizona Custom", "https://www.arizonacustomknives.com/", "Custom knife gallery", "Knife Making")
add("Jantz Supply", "https://www.jantzsupply.com/", "Knife making supplies", "Knife Making")
add("USA Knife Maker", "https://usaknifemaker.com/", "Knifemaking materials", "Knife Making")
add("Knife Steel Nerds", "https://knifesteelnerds.com/", "Knife steel metallurgy", "Knife Making")
add("British Blades", "https://britishblades.com/", "UK knife making community", "Knife Making")
add("Blade Show", "https://bladeshow.com/", "Knife trade show", "Knife Making")

# ============ PARKOUR ============
add("Parkour World", "https://parkour.world/", "International parkour", "Parkour")
add("ParkourED", "https://parkouredu.com/", "Parkour training education", "Parkour")
add("American Parkour", "https://www.americanparkour.com/", "US parkour tutorials", "Parkour")
add("Movement Creative", "https://www.themovementcreative.com/", "Parkour culture media", "Parkour")
add("Urban Freeflow", "https://www.urbanfreeflow.com/", "Parkour forum community", "Parkour")
add("MovNat", "https://www.movnat.com/", "Natural movement training", "Parkour")
add("PK Generations", "https://www.pkgenerations.com/", "Parkour history culture", "Parkour")

# ============ FENCING ============
add("FIE", "https://fie.org/", "International fencing federation", "Fencing")
add("USA Fencing", "https://www.usafencing.org/", "US fencing governing", "Fencing")
add("British Fencing", "https://www.britishfencing.com/", "UK fencing association", "Fencing")
add("Fencing.Net", "https://www.fencing.net/", "Fencing community forums", "Fencing")
add("Leon Paul", "https://www.leonpaul.com/", "Fencing equipment", "Fencing")
add("HEMA Alliance", "https://www.hemaalliance.com/", "Historical martial arts", "Fencing")
add("Wiktenauer", "https://wiktenauer.com/", "Historical fencing library", "Fencing")
add("Absolute Fencing", "https://www.absolutefencinggear.com/", "Fencing equipment retailer", "Fencing")

# ============ SOAP MAKING ============
add("Soap Queen", "https://www.soapqueen.com/", "Cold process soap tutorials", "Soap Making")
add("Bramble Berry", "https://www.brambleberry.com/", "Soap making supplies", "Soap Making")
add("Teach Soap", "https://www.teachsoap.com/", "Soap classes tutorials", "Soap Making")
add("Soap Making Forum", "https://www.soapmakingforum.com/", "Soap community Q&A", "Soap Making")
add("Lovin Soap", "https://www.lovinsoap.com/", "Soap recipes business tips", "Soap Making")
add("Modern Soap Making", "https://www.modernsoapmaking.com/", "Soap techniques tutorials", "Soap Making")
add("Wholesale Supplies Plus", "https://www.wholesalesuppliesplus.com/", "Soap candle supplies", "Soap Making")
add("The Nova Studio", "https://www.thenovastudio.com/", "Soap making classes", "Soap Making")

# ============ CANDLE MAKING ============
add("Candle Science", "https://www.candlescience.com/", "Candle making supplies", "Candle Making")
add("The Candle Source", "https://www.thecandlesource.com/", "Candle products classes", "Candle Making")
add("Candle Tech", "https://www.candletech.com/", "Candle equipment testing", "Candle Making")
add("Lonestar Candle", "https://lonestarcandlesupply.com/", "Candle wax fragrances", "Candle Making")
add("Candle Making Forum", "https://www.candlemakingforum.com/", "Candle making community", "Candle Making")
add("Arizona Candle Supply", "https://arizonacandlesupply.com/", "Candle containers supplies", "Candle Making")

# ============ BOOKBINDING ============
add("DAS Bookbinding", "https://www.dasbookbinding.com/", "Professional bookbinding", "Bookbinding & Paper Crafts")
add("Talas", "https://www.talasonline.com/", "Bookbinding supplies tools", "Bookbinding & Paper Crafts")
add("iBookBinding", "https://www.ibookbinding.com/", "Bookbinding guide community", "Bookbinding & Paper Crafts")
add("Society of Bookbinders", "https://www.societyofbookbinders.com/", "UK bookbinding organization", "Bookbinding & Paper Crafts")
add("Hollanders", "https://www.hollanders.com/", "Bookbinding supplies since 1968", "Bookbinding & Paper Crafts")
add("Colophon Book Arts", "https://colophonbookarts.com/", "Book arts letterpress", "Bookbinding & Paper Crafts")
add("Paper Connection", "https://www.paperconnection.com/", "Japanese paper bookbinding", "Bookbinding & Paper Crafts")

# ============ WEATHER ============
add("Weather Underground", "https://www.wunderground.com/", "Hyperlocal weather", "Weather")
add("Windy", "https://www.windy.com/", "Interactive weather map", "Weather")
add("NOAA Weather", "https://www.weather.gov/", "US National Weather Service", "Weather")
add("AccuWeather", "https://www.accuweather.com/", "Global weather alerts", "Weather")
add("Ventusky", "https://www.ventusky.com/", "Live wind weather map", "Weather")
add("OpenWeatherMap", "https://openweathermap.org/", "Free weather API", "Weather")
add("Meteoblue", "https://www.meteoblue.com/", "Detailed weather models", "Weather")
add("YR Norway", "https://www.yr.no/", "Norwegian weather service", "Weather")
add("AEMET", "https://www.aemet.es/", "Spanish met office", "Weather")
add("UK Met Office", "https://www.metoffice.gov.uk/", "UK national weather", "Weather")
add("Buoyweather", "https://www.buoyweather.com/", "Marine wave forecasts", "Weather")

# ============ POTTERY & CERAMICS ============
add("Ceramic Arts Network", "https://ceramicartsnetwork.org/", "Pottery techniques community", "Pottery & Ceramics")
add("Digital Fire", "https://digitalfire.com/", "Ceramic glaze database", "Pottery & Ceramics")
add("Glazy", "https://glazy.org/", "Open-source glaze calculator", "Pottery & Ceramics")
add("Ceramics.org", "https://www.ceramics.org/", "American Ceramic Society", "Pottery & Ceramics")
add("Ceramic School", "https://ceramic.school/", "Online pottery classes", "Pottery & Ceramics")
add("Sue McLeod Ceramics", "https://www.suemcleodceramics.com/", "Glaze tutorials", "Pottery & Ceramics")
add("KP Pottery", "https://www.kppottery.com/", "Pottery wheel tutorials", "Pottery & Ceramics")

# ============ MUSIC PRODUCTION ============
add("FL Studio", "https://www.image-line.com/", "Popular digital audio workstation", "Music Production")
add("Ableton", "https://www.ableton.com/", "Professional music production", "Music Production")
add("Audacity", "https://www.audacityteam.org/", "Free audio editor", "Music Production")
add("LMMS", "https://lmms.io/", "Free music production software", "Music Production")
add("REAPER", "https://www.reaper.fm/", "Affordable DAW", "Music Production")
add("KVR Audio", "https://www.kvraudio.com/", "Plugin database community", "Music Production")
add("BandLab", "https://www.bandlab.com/", "Free online music creation", "Music Production")
add("Splice", "https://splice.com/", "Sample library tools", "Music Production")
add("Vital Audio", "https://vital.audio/", "Free wavetable synth", "Music Production")
add("Native Instruments", "https://www.native-instruments.com/", "Music hardware software", "Music Production")

# ============ VINTAGE CARS ============
add("Hemmings", "https://www.hemmings.com/", "Classic car marketplace", "Vintage Cars")
add("Bring a Trailer", "https://bringatrailer.com/", "Enthusiast car auctions", "Vintage Cars")
add("Hagerty", "https://www.hagerty.com/", "Classic car insurance", "Vintage Cars")
add("Mecum Auctions", "https://www.mecum.com/", "Classic car auctions", "Vintage Cars")
add("Car and Classic", "https://www.carandclassic.com/", "European classic marketplace", "Vintage Cars")
add("Bonhams Cars", "https://www.bonhams.com/auctions/cars/", "Vintage car auctions", "Vintage Cars")
add("RM Sotheby's", "https://rmsothebys.com/", "Classic car specialist", "Vintage Cars")
add("Classic Car Weekly", "https://www.classiccarweekly.net/", "Restoration guides", "Vintage Cars")

# ============ FILM MAKING ============
add("No Film School", "https://nofilmschool.com/", "Independent filmmaking", "Film Making")
add("IndieWire", "https://www.indiewire.com/", "Independent film news", "Film Making")
add("Filmmaker Magazine", "https://filmmakermagazine.com/", "Film production indie", "Film Making")
add("DaVinci Resolve", "https://www.blackmagicdesign.com/products/davinciresolve", "Pro video editing", "Film Making")
add("CineD", "https://www.cined.com/", "Cinematography camera news", "Film Making")
add("StudioBinder", "https://www.studiobinder.com/", "Film production management", "Film Making")
add("Shotdeck", "https://shotdeck.com/", "Film frame reference", "Film Making")
add("Frame.io", "https://frame.io/", "Video review collaboration", "Film Making")
add("American Cinematographer", "https://theasc.com/", "Cinematography magazine", "Film Making")
add("Blackmagic Design", "https://www.blackmagicdesign.com/", "Cinema cameras", "Film Making")

# ============ ASTROPHOTOGRAPHY ============
add("PixInsight", "https://pixinsight.com/", "Astrophotography processing", "Astrophotography")
add("DeepSkyStacker", "https://deepskystacker.free.fr/", "Free astro stacking", "Astrophotography")
add("StarTools", "https://www.startools.org/", "Astrophotography processing", "Astrophotography")
add("TWAN", "https://twanight.org/", "Night sky photography", "Astrophotography")
add("Capture the Atlas", "https://capturetheatlas.com/", "Milky Way photography", "Astrophotography")
add("Lonely Speck", "https://www.lonelyspeck.com/", "Milky Way tutorials", "Astrophotography")
add("NightScape", "https://nightscape.photography/", "Nightscape tutorials", "Astrophotography")

# ============ COIN COLLECTING ============
add("NGC Coin", "https://www.ngccoin.com/", "Coin grading service", "Coin Collecting")
add("PCGS Coin", "https://www.pcgs.com/", "Coin grading service", "Coin Collecting")
add("CoinWorld", "https://www.coinworld.com/", "Coin collecting news", "Coin Collecting")
add("Numista", "https://en.numista.com/", "World coin catalog", "Coin Collecting")
add("CoinTalk", "https://www.cointalk.com/", "Coin collecting forum", "Coin Collecting")
add("Heritage Auctions", "https://www.ha.com/", "Coin auction house", "Coin Collecting")
add("Coinflation", "https://www.coinflation.com/", "Coin melt values", "Coin Collecting")
add("ANA", "https://www.money.org/", "American Numismatic Association", "Coin Collecting")

# ============ BREAD BAKING ============
add("The Perfect Loaf", "https://www.theperfectloaf.com/", "Sourdough bread recipes", "Bread Baking")
add("Bake with Jack", "https://bakewithjack.co.uk/", "Bread baking tutorials", "Bread Baking")
add("Flour Water Salt Yeast", "https://kensartisan.com/", "Artisan bread resources", "Bread Baking")
add("The Bread Kitchen", "https://www.thebreadkitchen.com/", "Bread making guides", "Bread Baking")
add("Breadtopia", "https://breadtopia.com/", "Sourdough baking resources", "Bread Baking")
add("Fresh Loaf", "https://www.thefreshloaf.com/", "Bread baking community", "Bread Baking")
add("King Arthur Baker's Hotline", "https://www.kingarthurbaking.com/baking-hotline", "Baking help line", "Bread Baking")
add("ChainBaker", "https://www.chainbaker.com/", "Bread baking techniques", "Bread Baking")
add("Simplify Baking", "https://simplifybaking.com/", "Simple bread recipes", "Bread Baking")

# ============ CHEESEMAKING ============
add("Cheese.com", "https://www.cheese.com/", "Cheese types database", "Cheesemaking")
add("New England Cheesemaking", "https://cheesemaking.com/", "Cheese making supplies", "Cheesemaking")
add("Cheese Forum", "https://cheeseforum.org/", "Cheesemaking community", "Cheesemaking")
add("Little Green Cheese", "https://littlegreencheese.com/", "Home cheesemaking tutorials", "Cheesemaking")
add("Gavin Webber Cheesemaking", "https://www.gavinwebber.com/", "Cheesemaking videos recipes", "Cheesemaking")
add("Cultures for Health", "https://www.culturesforhealth.com/", "Cheese cultures supplies", "Cheesemaking")
add("The Art of Cheese", "https://theartofcheese.com/", "Cheesemaking guides", "Cheesemaking")
add("Mad Millie", "https://www.madmillie.com/", "Cheesemaking kits", "Cheesemaking")

# ============ FERMENTATION ============
add("Wild Fermentation", "https://www.wildfermentation.com/", "Fermentation community", "Fermentation")
add("Fermented Food Lab", "https://www.fermentedfoodlab.com/", "Fermentation recipes", "Fermentation")
add("Cultures For Health", "https://www.culturesforhealth.com/", "Fermentation cultures", "Fermentation")
add("Noma Fermentation", "https://nomaferments.com/", "Noma guide to fermentation", "Fermentation")
add("Fermentation Podcast", "https://www.fermentationpodcast.com/", "Fermentation discussions", "Fermentation")
add("Mountain Feed", "https://mountainfeed.com/", "Fermentation supplies", "Fermentation")
add("Fermentools", "https://fermentools.com/", "Fermentation equipment", "Fermentation")
add("Make Sauerkraut", "https://www.makesauerkraut.com/", "Sauerkraut guides recipes", "Fermentation")

# ============ MEAT SMOKING ============
add("Amazing Ribs", "https://amazingribs.com/", "BBQ smoking science", "Meat Smoking")
add("Smoking Meat Forums", "https://www.smokingmeatforums.com/", "Smoking community", "Meat Smoking")
add("Meathead's AmazingRibs", "https://amazingribs.com/", "Meat smoking guide", "Meat Smoking")
add("BBQ Pit Boys", "https://bbqpitboys.com/", "BBQ smoking recipes", "Meat Smoking")
add("Smoke Trails", "https://smoketrails.com/", "Smoking tips techniques", "Meat Smoking")
add("Hey Grill Hey", "https://heygrillhey.com/", "BBQ smoking recipes", "Meat Smoking")
add("Grill Grates", "https://grillgrate.com/", "Grilling smoking guides", "Meat Smoking")

# ============ BONSAI ============
add("Bonsai Empire", "https://www.bonsaiempire.com/", "Bonsai care guides", "Bonsai")
add("Bonsai Tonight", "https://bonsaitonight.com/", "Bonsai techniques news", "Bonsai")
add("Bonsai Nut", "https://www.bonsainut.com/", "Bonsai community forum", "Bonsai")
add("BSSF", "https://www.bssf.org/", "Bonsai Society of San Francisco", "Bonsai")
add("Bonsai4Me", "https://bonsai4me.com/", "Bonsai species guides", "Bonsai")
add("Bonsai Resource Center", "https://bonsairesourcecenter.com/", "Bonsai beginner guides", "Bonsai")
add("Valavanis Bonsai", "https://www.valavanisbonsai.com/", "Bonsai history articles", "Bonsai")

# ============ COCKTAILS ============
add("Difford's Guide", "https://www.diffordsguide.com/", "Cocktail recipes encyclopedia", "Cocktails")
add("Punch Drink", "https://punchdrink.com/", "Cocktail culture news", "Cocktails")
add("Liquor.com", "https://www.liquor.com/", "Cocktail recipes tips", "Cocktails")
add("Imbibe Magazine", "https://imbibemagazine.com/", "Cocktail magazine", "Cocktails")
add("Kindred Cocktails", "https://kindredcocktails.com/", "Cocktail database", "Cocktails")
add("Cocktail Chemistry", "https://www.cocktailchemistry.com/", "Cocktail science videos", "Cocktails")
add("Educated Barfly", "https://educatedbarfly.com/", "Cocktail recipes technique", "Cocktails")
add("Total Tiki", "https://totaltiki.net/", "Tiki cocktail resource", "Cocktails")
add("The Cocktail Project", "https://www.thecocktailproject.com/", "Cocktail making guides", "Cocktails")
add("Alpenz", "https://alpenz.com/", "Aperitif spirits guide", "Cocktails")

# ============ GENEALOGY (already above) ============
# Done

# Now write all changes
print(f"New links to add: {added}")
print(f"Existing links: {len(links)}")

links.extend(new_links_list)

with open(LINKS_FILE, 'w', encoding='utf-8') as f:
    json.dump(links, f, ensure_ascii=False, indent=2)

with open(JS_FILE, 'w', encoding='utf-8') as f:
    js_content = f'const linksData = {json.dumps(links, ensure_ascii=False)};\n'
    f.write(js_content)

print(f"Saved: {len(links)} total links ({added} new)")
